### ISSUE TITLE
Dataset Typo

### ISSUE THREAD

**Issue by adrian-jaques-b** [huijelee/ELF22#1]
Hello and thank you for sharing your work!

I just wanted to mention that you have a typo in your dataset description in the README.md:

![image](https://user-images.githubusercontent.com/68905111/185861364-4deef96f-f778-4219-b97d-44c6143b5c81.png)
![image](https://user-images.githubusercontent.com/68905111/185861476-c725e2eb-a945-4e54-b260-70aca5111bf8.png)

I checked it and the numbers in the paper are right. 

Kind regards, Jaqu

**Comment by huijelee** [comment]
Hello, Jaqu!

There are some typos in the numbers of 'Engage' samples.
(2,331, 340, 343, 2,817) -> (2,134, 340, 343, 2,817)

```
import json
import pandas as pd

df = pd.read_json('data/train.json')
print(df[df['ResponseL'] == 1])
```

Thank you for the correction. 

Warm Regards,
Huije Lee
